name: test

on: [push]

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]

    runs-on: ${{ matrix.os }}

    env:
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        id: node_modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-npm-

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm test
